repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
        additional_dependencies: [oganesson-py]
  
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.11